version: '3.8'

services:
  postgres:
    image: postgres:${PG_DB_VERSION}
    container_name: ${DB_CONTAINER}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5151:80"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  minio:
    image: minio/minio:${MINIO_VERSION}
    container_name: minio
    restart: always
    ports:
      - "9100:9000"  # MinIO API
      - "9101:9001"  # MinIO Console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
  pgadmin-data: